/**
 * generated by Xtext
 */
package org.polarsys.chess.xtext.validation;

import org.polarsys.chess.xtext.validation.AbstractFlaDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FlaDslValidator extends AbstractFlaDslValidator {
}
