<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chessmlprofile" nsURI="http://CHESS" nsPrefix="CHESS">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="CHESS"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="dummy"/>
  <eSubpackages name="Core" nsURI="http://CHESS/Core" nsPrefix="Core">
    <eClassifiers xsi:type="ecore:EClass" name="CHESS">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Model" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Model"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysisView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/AnalysisView" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deploymentView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/DeploymentView" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requirementView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/RequirementView" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/ComponentView" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/SystemView" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="psmView" ordered="false"
          lowerBound="1" eType="#//Core/CHESSViews/PSMView"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" ordered="false"
          lowerBound="1" eType="#//Core/Domain"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Domain">
      <eLiterals name="cross_domain"/>
      <eLiterals name="avionics" value="1"/>
      <eLiterals name="automotive" value="2"/>
      <eLiterals name="telecom" value="3"/>
      <eLiterals name="space" value="4"/>
      <eLiterals name="medical" value="5"/>
      <eLiterals name="petroleum" value="6"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CHGaResourcePlatform" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaResourcesPlatform">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
          ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PSMPackage">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AnalysisContext" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/SAM/SaAnalysisContext"/>
    </eClassifiers>
    <eSubpackages name="CHESSViews" nsURI="http://CHESS/Core/Views" nsPrefix="CHESSViews">
      <eClassifiers xsi:type="ecore:EClass" name="ExtraFunctionalView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="timingdataflowview"
            ordered="false" lowerBound="1" eType="#//Core/CHESSViews/TimingDataFlowView"
            containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimingDataFlowView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RTAnalysisView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DeploymentView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="AssignList" ordered="false"
            upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RequirementView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComponentView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DependabilityAnalysisView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SystemView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PSMView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AnalysisView">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="rtanalysisview" ordered="false"
            lowerBound="1" eType="#//Core/CHESSViews/RTAnalysisView" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="depanalysisview" ordered="false"
            lowerBound="1" eType="#//Core/CHESSViews/DependabilityAnalysisView"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Dependability" nsURI="http:///CHESS/Dependability.ecore" nsPrefix="CHESS.Dependability">
    <eSubpackages name="FailurePropagation" nsURI="http://CHESS/Dependability/FailurePropagation"
        nsPrefix="FailurePropagation">
      <eClassifiers xsi:type="ecore:EClass" name="FPTCSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="this allows to work with FPTC at instance level by using composite diagrams. It allows to decorate ports of the parts.&#xD;&#xA;attribute 'failure' is deprecated, use 'failureModes'"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="failure" ordered="false"
            upperBound="-1" eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/FailureType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="partWithPort" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="failureMode" ordered="false"
            upperBound="-1" eType="#//Dependability/DependableComponent/FailureMode"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FPTCPortSlot">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="deprecated, use FailureModes"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="FPTCSpecification"
            ordered="false" lowerBound="1" eType="#//Dependability/FailurePropagation/FPTCSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Slot" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="failure" ordered="false"
            upperBound="-1" eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/FailureType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FPTC" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="deprecated, use FLABehavior instead&#xD;&#xA;"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fptc" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FLABehavior">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="replace the old FPTC stereotype"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fptc" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FailurePropagationAnalysis" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaAnalysisContext"/>
      <eClassifiers xsi:type="ecore:EClass" name="FI4FA" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fi4fa" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FI4FASpecification" eSuperTypes="#//Dependability/FailurePropagation/FPTCSpecification"/>
      <eClassifiers xsi:type="ecore:EClass" name="ACIDAvoidable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/A_avoidable"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="c" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/C_avoidable"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="i" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/I_avoidable"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/D_avoidable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ACIDMitigation">
        <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
          <details key="originalName" value="ACIDMitigation "/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/A_mitigation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="c" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/C_mitigation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="i" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/I_mitigation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="d" ordered="false"
            eType="#//Dependability/FailurePropagation/FailurePropagationDataTypes/D_mitigation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FI4FAAnalysis" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaAnalysisContext"/>
      <eSubpackages name="FailurePropagationDataTypes" nsURI="http:///CHESS/Dependability/FailurePropagation/FailurePropagationDataTypes.ecore"
          nsPrefix="CHESS.Dependability.FailurePropagation.FailurePropagationDataTypes">
        <eClassifiers xsi:type="ecore:EEnum" name="D_avoidable">
          <eLiterals name="unspecified"/>
          <eLiterals name="impermanence" value="1"/>
          <eLiterals name="none" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="I_avoidable">
          <eLiterals name="unspecified"/>
          <eLiterals name="interference" value="1"/>
          <eLiterals name="none" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="C_avoidable">
          <eLiterals name="unspecified"/>
          <eLiterals name="inconsistency" value="1"/>
          <eLiterals name="none" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="A_avoidable">
          <eLiterals name="unspecified"/>
          <eLiterals name="incompletion" value="1"/>
          <eLiterals name="none" value="2"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="A_mitigation">
          <eLiterals name="unspecified"/>
          <eLiterals name="all_or_nothing" value="1"/>
          <eLiterals name="all_or_compensation" value="2"/>
          <eLiterals name="none" value="3"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="C_mitigation">
          <eLiterals name="unspecified"/>
          <eLiterals name="full_consistency" value="1"/>
          <eLiterals name="range_violation_allowed" value="2"/>
          <eLiterals name="none" value="3"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="I_mitigation">
          <eLiterals name="unspecified"/>
          <eLiterals name="portable_level" value="1"/>
          <eLiterals name="serializable" value="2"/>
          <eLiterals name="none" value="3"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="D_mitigation">
          <eLiterals name="unspecified"/>
          <eLiterals name="no_loss" value="1"/>
          <eLiterals name="partial_loss_allowed" value="2"/>
          <eLiterals name="none" value="3"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EEnum" name="FailureType">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="deprecated, use FailureMode"/>
          </eAnnotations>
          <eLiterals name="late"/>
          <eLiterals name="early" value="1"/>
          <eLiterals name="valueSubtle" value="2"/>
          <eLiterals name="valueCoarse" value="3"/>
          <eLiterals name="omission" value="4"/>
          <eLiterals name="commission" value="5"/>
          <eLiterals name="noFailure" value="6"/>
          <eLiterals name="variable" value="7"/>
          <eLiterals name="wildcard" value="8"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="DependableComponent" nsURI="http://CHESS/Dependability/DependableComponent"
        nsPrefix="DependableComponent">
      <eClassifiers xsi:type="ecore:EClass" name="FailureModes">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="allows to decorate a port\instance with information regarding the failureModes/threats possibly affecting the port\instance itself&#xD;&#xA;if applied at the same time on the same entity, than each FailureMode referred by Threats.failureMode must be referred also by FailureModes.failureMode"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Slot" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="failureMode" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//Dependability/DependableComponent/FailureMode"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="FPTCSpecification"
            ordered="false" eType="#//Dependability/FailurePropagation/FPTCSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DependableComponent">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="obsolete, use ErrorModelBehavior"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="errorModel" ordered="false"
            upperBound="-1" eType="#//Dependability/ThreatsPropagation/ErrorModel"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="AttackType">
        <eLiterals name="masqueradeAttack"/>
        <eLiterals name="denialOfServiceAttack" value="1"/>
        <eLiterals name="bruteForceAttack" value="2"/>
        <eLiterals name="dataSpoofingAttack" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="VulnerabilityType">
        <eLiterals name="missingDataIntegritySchemes"/>
        <eLiterals name="inadequateEncryptionStrength" value="1"/>
        <eLiterals name="resourceAllocationWithoutLimits" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ThreatType">
        <eLiterals name="unauthorizedAccessOfService"/>
        <eLiterals name="unauthorizedModificationOfService" value="1"/>
        <eLiterals name="unauthorizedDenialOfService" value="2"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ErrorModelBehavior">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This stereotype is used to attach a user defined error model to an architectural element. It replaces the DependableComponent.&#xD;&#xA;See also FLABehavior and SimpleStochasticBehavior."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="errorModel" ordered="false"
            upperBound="-1" eType="#//Dependability/ThreatsPropagation/ErrorModel"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Threat">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="if applied at the same time on the same entity, than each FailureMode referred by Threats.failureMode must be referred also by FailureModes.failureMode"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="failuremode" ordered="false"
            lowerBound="1" upperBound="-1" eType="#//Dependability/DependableComponent/FailureMode"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Slot" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
            lowerBound="1" eType="#//Dependability/DependableComponent/ThreatType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Propagation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prob" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FailureMode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="UMLConstraints can be attached to FailureMode to specify compliance between them (to be confirmed). FailureModes can appear in generalization relationships; in this case the compatibility between FailureMmodes follows the UML generalization semantics."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="exposure" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="controllability" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="likelihood "/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="ThreatsPropagation" nsURI="http://CHESS/Dependability/ThreatsPropagation"
        nsPrefix="ThreatsPropagation">
      <eClassifiers xsi:type="ecore:EClass" name="DegradedState" eSuperTypes="#//Dependability/ThreatsPropagation/ThreatState">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="New Dep profile"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ThreatState">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NormalState">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="New Dep profile"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ErrorState" eSuperTypes="#//Dependability/ThreatsPropagation/ThreatState"/>
      <eClassifiers xsi:type="ecore:EClass" name="StuckAt">
        <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StuckAtFixed">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Inverted">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RampDown">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_State" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//State"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="property" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="decr" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="endValue" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NormalInput" eSuperTypes="#//Dependability/ThreatsPropagation/DepEvent"/>
      <eClassifiers xsi:type="ecore:EClass" name="DepEvent" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false"
            eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NormalOutput" eSuperTypes="#//Dependability/ThreatsPropagation/DepEvent"/>
      <eClassifiers xsi:type="ecore:EClass" name="Failure">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" ordered="false"
            lowerBound="1" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InternalFault">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occurrence" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InternalPropagation">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalFaults" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="RecoveryKind">
        <eLiterals name="Repair"/>
        <eLiterals name="Compensation" value="1"/>
        <eLiterals name="ErrorDetection" value="2"/>
        <eLiterals name="Reconfiguration" value="3"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ErrorDetection">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="successProbability"
            ordered="false" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ErrorHandling">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="successProbability"
            ordered="false" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FaultHandling">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Transition" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Transition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="delay" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="successProbability"
            ordered="false" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Attack" eSuperTypes="#//Dependability/ThreatsPropagation/InternalPropagation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
            lowerBound="1" eType="#//Dependability/DependableComponent/AttackType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerability" ordered="false"
            lowerBound="1" eType="#//Dependability/ThreatsPropagation/Vulnerability"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="threat" ordered="false"
            lowerBound="1" eType="#//Dependability/DependableComponent/ThreatType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Vulnerability" eSuperTypes="#//Dependability/ThreatsPropagation/InternalFault">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" ordered="false"
            lowerBound="1" eType="#//Dependability/DependableComponent/VulnerabilityType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ErrorModel">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_StateMachine"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//StateMachine"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="StateBased" nsURI="http://CHESS/Dependability/StateBased"
        nsPrefix="StateBased">
      <eSubpackages name="StateBasedDataTypes" nsURI="http:///CHESS/Dependability/StateBased/StateBasedDataTypes.ecore"
          nsPrefix="CHESS.Dependability.StateBased.StateBasedDataTypes">
        <eClassifiers xsi:type="ecore:EEnum" name="RedundancyKind">
          <eLiterals name="TMR"/>
          <eLiterals name="Recovery" value="1"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="DependabilityMeasure"/>
        <eClassifiers xsi:type="ecore:EClass" name="EvaluationMethod"/>
        <eClassifiers xsi:type="ecore:EClass" name="EvaluationBySimulation" eSuperTypes="#//Dependability/StateBased/StateBasedDataTypes/EvaluationMethod"/>
        <eClassifiers xsi:type="ecore:EEnum" name="ConfidenceKind">
          <eLiterals name="relative"/>
          <eLiterals name="absolute" value="1"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="EvaluationAnalytical" eSuperTypes="#//Dependability/StateBased/StateBasedDataTypes/EvaluationMethod"/>
        <eClassifiers xsi:type="ecore:EClass" name="Reliability" eSuperTypes="#//Dependability/StateBased/StateBasedDataTypes/DependabilityMeasure"/>
        <eClassifiers xsi:type="ecore:EClass" name="EvaluationType"/>
        <eClassifiers xsi:type="ecore:EClass" name="SteadyState"/>
        <eClassifiers xsi:type="ecore:EClass" name="Availability" eSuperTypes="#//Dependability/StateBased/StateBasedDataTypes/DependabilityMeasure"/>
        <eClassifiers xsi:type="ecore:EClass" name="MTTF" eSuperTypes="#//Dependability/StateBased/StateBasedDataTypes/DependabilityMeasure"/>
      </eSubpackages>
      <eSubpackages name="StateBasedComponents" nsURI="http://CHESS/Dependability/StateBased/StateBasedComponents"
          nsPrefix="StateBasedComponents">
        <eClassifiers xsi:type="ecore:EClass" name="StochasticFailureBehaviour" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="to be removed???"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureDistribution"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="repairDistribution"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="modes" ordered="false"
              lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StatefulHardware" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="obsolete, see SimpleStochasticBehaviour"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="probPermFault" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorLatency" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="repairDelay" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultOcc" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StatelessSoftware" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="obsolete, see SimpleStochasticBehaviour"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultOcc" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StatelessHardware" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="obsolete, see SimpleStochasticBehaviour"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="probPermFault" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="repairDelay" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultOcc" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="StatefulSoftware" eSuperTypes="#//Dependability/DependableComponent/DependableComponent">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="obsolete, see SimpleStochasticBehaviour"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="errorLatency" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="repairDelay" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultOcc" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Frequency"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SimpleStochasticBehavior">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
              ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureOccurrence"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real">
            <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
              <details key="originalName" value="failureOccurrence "/>
            </eAnnotations>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="repairDelay" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureModesDistribution"
              ordered="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="FaultTolerance" nsURI="http://CHESS/Dependability/StateBased/FaultTolerance"
          nsPrefix="FaultTolerance">
        <eClassifiers xsi:type="ecore:EClass" name="FaultTolerant">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheme" ordered="false"
              lowerBound="1" eType="#//Dependability/StateBased/StateBasedDataTypes/RedundancyKind"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="schemeAttrs" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//OpaqueExpression"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="RedundancyManager">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheme" ordered="false"
              lowerBound="1" eType="#//Dependability/StateBased/StateBasedDataTypes/RedundancyKind"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Variant">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Adjudicator">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" ordered="false"
              lowerBound="1" eType="ecore:EDataType ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//MARTE_PrimitivesTypes/Real"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="MaintenanceMonitoring" nsURI="http://CHESS/Dependability/StateBased/MaintenanceMonitoring"
          nsPrefix="MaintenanceMonitoring">
        <eClassifiers xsi:type="ecore:EClass" name="MMActivities">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Activity" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" ordered="false"
              eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="probSuccess" ordered="false"
              lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="onCompletion" ordered="false"
              upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="onSuccessfulCompletion"
              ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="onFailedCompletion"
              ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Action" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Action"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Repair" eSuperTypes="#//Dependability/StateBased/MaintenanceMonitoring/MMActivities">
          <eStructuralFeatures xsi:type="ecore:EReference" name="targets" ordered="false"
              lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="Replace" eSuperTypes="#//Dependability/StateBased/MaintenanceMonitoring/MMActivities">
          <eStructuralFeatures xsi:type="ecore:EReference" name="targets" ordered="false"
              lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="replacement" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="ErrorDetection" eSuperTypes="#//Dependability/StateBased/MaintenanceMonitoring/MMActivities">
          <eStructuralFeatures xsi:type="ecore:EReference" name="targets" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctionProbability"
              ordered="false" lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="FailureDetection" eSuperTypes="#//Dependability/StateBased/MaintenanceMonitoring/MMActivities">
          <eStructuralFeatures xsi:type="ecore:EReference" name="onDetection" ordered="false"
              lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Activity"/>
        </eClassifiers>
      </eSubpackages>
      <eSubpackages name="StateBasedAnalysis" nsURI="http://CHESS/Dependability/StateBased/StateBasedAnalysis"
          nsPrefix="StateBasedAnalysis">
        <eClassifiers xsi:type="ecore:EClass" name="StateBasedAnalysis" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_AnalysisModel/GQAM/GaAnalysisContext">
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure" ordered="false"
              lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="measureEvaluationResult"
              ordered="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="evalMethod" ordered="false"
              eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFailureMode"
              ordered="false" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="targetDepComponent"
              ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" ordered="false"
              upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="initialConditions"
              ordered="false" upperBound="-1" eType="#//Dependability/StateBased/StateBasedAnalysis/SBAInitialConditions"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SBAInitialConditions">
          <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="targetInstance" ordered="false"
              lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="setup" ordered="false"
              lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="MitigationMeans" nsURI="http://CHESS.Dependability/MitigationMeans"
        nsPrefix="MitigationMeans">
      <eClassifiers xsi:type="ecore:EClass" name="TransmissionWithProtocol">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="CRC" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="UseSeqID" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Predictability" nsURI="http:///CHESS/Predictability.ecore" nsPrefix="CHESS.Predictability">
    <eSubpackages name="DeploymentConfiguration" nsURI="http://CHESS/Predictability/DeploymentConfiguration"
        nsPrefix="DeploymentConfiguration">
      <eSubpackages name="HardwareBaseline" nsURI="http://CHESS/Predictability/DeploymentConfiguration/HardwareBaseline"
          nsPrefix="HardwareBaseline">
        <eClassifiers xsi:type="ecore:EClass" name="CH_HwProcessor" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_DesignModel/HRM/HwLogical/HwComputing/HwProcessor">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="deprecated, to be replaced with MARTE HWProcessor"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CH_HwBus" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_DesignModel/HRM/HwLogical/HwCommunication/HwBus">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="to be reviewed"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="CH_HwComputingResource" eSuperTypes="../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_DesignModel/HRM/HwLogical/HwComputing/HwComputingResource">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="to be reviewed"/>
          </eAnnotations>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" ordered="false"
              eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
        </eClassifiers>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="RTComponentModel" nsURI="http://CHESS/Predictability/RTComponentModel"
        nsPrefix="RTComponentModel">
      <eClassifiers xsi:type="ecore:EClass" name="CHRtSpecification">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The following attributes are deprecated:&#xD;&#xA;-respT&#xD;&#xA;-blockT&#xD;&#xA;operationReqForSporadicOcc: the list of operations that need to be invoked to allow the sporadic occurrence of the &quot;context&quot; operation.&#xD;&#xA;&#xD;&#xA;Constraints:&#xD;&#xA;Only for sporadic occurrence kind.&#xD;&#xA;The operations in the list must be owned by the Component which owns the 'context' operation.&#xD;&#xA;If the list is not empty the &quot;context&quot; operation must have private visibility and it cannot be invoked directly by other operations.&#xD;&#xA;If the list is empty the &quot;context&quot; operation must be invoked directly by other operations.&#xD;&#xA;&#xD;&#xA;CHRtSpecification extends MARTE RtSpecification"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="partWithPort" ordered="false"
            unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="WCET" ordered="false"
            lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="localWCET" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePriority" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ceiling" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="memorySizeFootprint"
            ordered="false" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="stackSize" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="heapSize" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_DataSize"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false"
            eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="occKind" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/ArrivalPattern"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="protection" ordered="false"
            eType="ecore:EEnum ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_DesignModel/HLAM/CallConcurrencyKind"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rlDl" ordered="false"
            eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="context" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//BehavioralFeature"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="respT" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockT" ordered="false"
            upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Duration"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="operationReqForSporadicOcc"
            ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CHRtPortSlot">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="To be renamed with CHRtFeature, as extension of the MARTE RtFeature&#xD;&#xA;"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Slot" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Slot"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="cH_RtSpecification"
            ordered="false" upperBound="-1" eType="#//Predictability/RTComponentModel/CHRtSpecification"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
            ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RunTimeSupport">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="monitoring" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="verification" ordered="false"
            lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="ARINCComponentModel" nsURI="http://CHESS/Predictability/ARINCComponentModel"
        nsPrefix="ARINCComponentModel">
      <eClassifiers xsi:type="ecore:EClass" name="ARINCComponentImpl">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ARINCProcess">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationsGroups" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ARINCFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="followedBy" ordered="false"
            upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateDivider" ordered="false"
            eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Integer"
            defaultValueLiteral="1"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="ComponentModel" nsURI="http://CHESS/ComponentModel" nsPrefix="ComponentModel">
    <eClassifiers xsi:type="ecore:EClass" name="FunctionalPartition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Avioncs IMA concept"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="utilization" ordered="false"
          eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Real"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="MAF" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="MIF" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="SchedulingTable" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE_Library.ecore#//BasicNFP_Types/NFP_String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HwAbstractionComponentImpl">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="represents a SW interface for a given HW component; to hide hardware properties from higher software layers"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hwRes" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.papyrus.marte.static.profile/resources/MARTE.ecore#//MARTE_DesignModel/HRM/HwGeneral/HwResource"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentImplementation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Component" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Component"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
          eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OS" ordered="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceCodeLocation" ordered="false"
          upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="SystemModel" nsURI="http:///CHESS/SystemModel.ecore" nsPrefix="CHESS.SystemModel">
    <eSubpackages name="STS" nsURI="http://CHESS/SystemModel/STS" nsPrefix="STS">
      <eClassifiers xsi:type="ecore:EClass" name="Human">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Human structured classes can be decomposed in HumanActuatorUnits"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Organization">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Organization structured classes can be decompsosed in OrganizationUnits"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OrganizationUnit" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Technological">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TimePressure" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OUMissionManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OURulesRegulationManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OUClimateManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OUOversightManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OUProcessManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="OUResourceManagement" eSuperTypes="#//SystemModel/STS/OrganizationUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HSAttention" eSuperTypes="#//SystemModel/STS/HumanSensorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HumanSensorUnit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HSPerception" eSuperTypes="#//SystemModel/STS/HumanSensorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HSKnowledgePerception" eSuperTypes="#//SystemModel/STS/HumanSensorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HSSensory" eSuperTypes="#//SystemModel/STS/HumanSensorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HAFeedback" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HumanActuatorUnit" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="HAIntent" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HACommunication" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HATimeManagement" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HASelection" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HAResponse" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
      <eClassifiers xsi:type="ecore:EClass" name="HAKnowledgeDecision" eSuperTypes="#//SystemModel/STS/HumanActuatorUnit"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Safety" nsURI="http://CHESS/Safety" nsPrefix="Safety">
    <eClassifiers xsi:type="ecore:EClass" name="CriticalityInterfaceSpecification">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allows for a given provided port of a component instance to constrains the criticality level that a given component isntance must have in order to be able to access the port.&#xD;&#xA;In case of base Constraint, the constrained element must refer a provided port+ instance or a slot, the latter as instance of a provided port.&#xD;&#xA;In case of base Comment, its usage is the same of the CHRTSpecification."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="acceptedCriticalityForClients"
          ordered="false" upperBound="-1" eType="#//Safety/CriticalityLevel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CriticalityLevel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="isHigherThan" ordered="false"
          upperBound="-1" eType="#//Safety/CriticalityLevel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="mapsTo" ordered="false"
          upperBound="-1" eType="#//Safety/CriticalityLevel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CriticalitySpecification">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Constraint" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Constraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="criticalityLevel" ordered="false"
          lowerBound="1" eType="#//Safety/CriticalityLevel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hazard">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
