<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DEEM"
    nsURI="http://informatica.unifi.it/metamodels/deem" nsPrefix="deem">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayInfo" eType="#//Coordinates"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Net" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="#//Place" containment="true" eOpposite="#//Place/net"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputArcs" upperBound="-1"
        eType="#//InputArc" containment="true" eOpposite="#//InputArc/net"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputArcs" upperBound="-1"
        eType="#//OutputArc" containment="true" eOpposite="#//OutputArc/net"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/net"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputArc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" unique="false"
        lowerBound="1" eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" unique="false"
        lowerBound="1" eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//Net"
        eOpposite="#//Net/inputArcs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputArc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" unique="false"
        lowerBound="1" eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" unique="false"
        lowerBound="1" eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//Net"
        eOpposite="#//Net/outputArcs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//Net"
        eOpposite="#//Net/places"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marking" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="net" lowerBound="1" eType="#//Net"
        eOpposite="#//Net/transitions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="params" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//TransitionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImmediateTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArcType">
    <eLiterals name="Normal"/>
    <eLiterals name="Inhibitor" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionType">
    <eLiterals name="Deterministic"/>
    <eLiterals name="Exponential" value="1"/>
    <eLiterals name="Normal" value="11"/>
    <eLiterals name="Uniform" value="13"/>
    <eLiterals name="Gamma" value="3"/>
    <eLiterals name="Weibull" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InhibitorArc" eSuperTypes="#//OutputArc"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinates">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
