<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MeasuresOfInterest"
    nsURI="http://rcl.dsi.unifi.it/ecore/measures" nsPrefix="moi">
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="studies" lowerBound="1"
        upperBound="-1" eType="#//Study" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measures" lowerBound="1"
        upperBound="-1" eType="#//Measure" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Study" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Measure" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rewardFunction" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationType" lowerBound="1"
        eType="#//EvaluationType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarkingExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticBinaryOperator" abstract="true"
      eSuperTypes="#//ArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression2" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpSum" eSuperTypes="#//ArithmeticBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpMinus" eSuperTypes="#//ArithmeticBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpMultiply" eSuperTypes="#//ArithmeticBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpDivide" eSuperTypes="#//ArithmeticBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfThenElse" eSuperTypes="#//ArithmeticExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//LogicalExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifTrue" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ifFalse" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalBinaryOperator" abstract="true"
      eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression2" lowerBound="1"
        eType="#//ArithmeticExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpEqual" eSuperTypes="#//LogicalBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpGreater" eSuperTypes="#//LogicalBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpLess" eSuperTypes="#//LogicalBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpGreaterEqual" eSuperTypes="#//LogicalBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpLessEqual" eSuperTypes="#//LogicalBinaryOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpNot" eSuperTypes="#//LogicalExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//LogicalExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SteadyState" eSuperTypes="#//EvaluationType"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstantOfTime" eSuperTypes="#//EvaluationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalOfTime" abstract="true" eSuperTypes="#//EvaluationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalBegin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intervalEnd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalOfTimeCumulated" eSuperTypes="#//IntervalOfTime"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntervalOfTimeAveraged" eSuperTypes="#//IntervalOfTime"/>
</ecore:EPackage>
